// Generated by https://quicktype.io

export interface PokemonList {
  count: number;
  next: string | null;
  previous: string | null;
  results: BasicPokemon[];
}

export interface BasicPokemon {
  name: string;
  url: string;
}
