import { buildImage, takeCard, valueOfCard } from './';

/*
    executeTurn function requires id to identify the player ( human player or computer )
    calls takeCard function to get a card and with the value returned calls valueOfCard function
    and with the result updates the score of the current player, shows it to the user and add the img HTMl
    element generated by buildImage function
*/ 
export const executeTurn = ( id = 0, deck, score, scoreHTML, cardSectionHTML ) => {
    const lastCard = takeCard( deck );
    score[ id ] += valueOfCard( lastCard );
    scoreHTML[ id ].innerText = score[ id ];
    cardSectionHTML[ id ].append( buildImage( lastCard ) );
};
